name: Analysis-Sorting-Algorithms

on:
  workflow_dispatch:
    inputs:
      algorithm:
        description: 'Sorting algorithm to run'
        required: true
        default: 'insertion'
      number_of_inputs:
        description: 'Total number of inputs'
        required: true
        default: '100'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: python random_permutation.py ${{ github.event.inputs.number_of_inputs }} -b 5 > random.txt

      - run: javac Sort.java

      - run: ./run_sort.sh ${{ github.event.inputs.algorithm }} < random.txt