name: Analysis-Sorting-Algorithms

on:
  workflow_dispatch:
    inputs:
      number_of_inputs:
        description: 'Total number of inputs'
        required: true
        default: '1000'
      block_size:
        description: 'Block Size'
        required: true
        default: '1'
      input_file:
        description: 'Name of input file'
        required: true
        default: 'random.txt'

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        algorithm: ['insertion','merge','quick']
    steps:
      - uses: actions/checkout@v2

      - run: python random_permutation.py ${{ github.event.inputs.number_of_inputs }} -b ${{ github.event.inputs.block_size }} > random.txt

      - run: javac Sort.java

      - run: ./run_sort.sh ${{ matrix.algorithm }} < <(tac ${{ github.event.inputs.input_file }})